export enum Wallet {
  METAMASK_INJECTED = 'METAMASK_INJECTED',
  METAMASK = 'METAMASK',
  UNIPASS = 'UNIPASS',
  JOYID = 'JOYID',
  JOYID_WEB = 'JOYID_WEB',
  WALLETCONNECT = 'WALLETCONNECT',
}

export enum WalletType {
  EOA = 'EOA',
  AA = 'AA',
}
